### ISSUE TITLE
Update PowerShell and PS Analyzer

### ISSUE THREAD

**Issue by dmpe** [cardboardci/docker-psscriptanalyzer#1]
Hi, 
thank you for this work. 

Can we update this image to the newest versions available? 
I would be willing to create PR for this..
Thanks

**Comment by jrbeverly** [comment]
Hey, 
Thanks for taking a look.

I'll try to update the image today, but that'll probably involve moving away from alpine, and onto ubuntu. I'm planning to move most of the images in this organization over to a common ubuntu image (so they all have up to date dependencies). Don't know if that will still meet your requirements.

At the moment I'm trying to setup a github action to automatically update dependencies based on scripts in the repository (e.g. `bash update-deps && git add * && ...`)

**Comment by dmpe** [comment]
Hi, 
this would be great. no issue for me whatsoever. Will be looking forward to it. 
Thanks.

**Comment by jrbeverly** [comment]
This work should be resolved now (although I lot later than I anticipated 🐌 ). The results from a version dump of the latest image are:

`docker run -it cardboardci/psscriptanalyzer pwsh -Command '$PSVersionTable'`
```bash
Name                           Value
----                           -----
PSVersion                      6.2.3
PSEdition                      Core
GitCommitId                    6.2.3
OS                             Linux 4.9.184-linuxkit #1 SMP Tue Jul 2 22:58:16 UTC 2019
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

`docker run -it cardboardci/psscriptanalyzer pwsh -Command 'Get-InstalledModule'`
```bash

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.18.3               PSScriptAnalyzer                    PSGallery            PSScriptAnalyzer provides script analysis and checks for potential code defects in the scripts by … 

```

I hope to refactor the changes a bit more so they can be upgraded on routine by a github workflow
